spring.application.name=retailmanagement
# Server Configuration
server.port=8080
#server.port=${PORT:8080}

# Database Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=retail_management_v5;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.task.scheduling.enabled=true
# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.dao=ERROR
logging.level.com.retailmanagement=DEBUG

# Jackson Configuration
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method

server.tomcat.max-parameter-count=10000
server.tomcat.max-part-count=1000
server.tomcat.max-swallow-size=-1
# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# JWT Configuration
app.jwt.secret=mySecretKeyForJWTTokenGenerationMustBe256BitsLongOrMoreForHS256Algorithm
app.jwt.expiration=86400000
# Resend Configuration
#resend.api.key=${RESEND_API}
resend.api.key=re_EjKat9Er_JPPNohBVXZtD9fze1g7CUNHD

#groq.api-key=${GROQ_API}
groq.api-key=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
spring.task.scheduling.pool.size=5


logging.level.org.springframework.context=DEBUG
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.hibernate.engine.jdbc.spi=DEBUG

cloudinary.cloud-name=dvgirglbc
cloudinary.api-key=976951218127679
cloudinary.api-secret=e4e_EElwS7j6umWuFu-kdX3Gd40
#cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
#cloudinary.api-key=${CLOUDINARY_API_KEY}
#cloudinary.api-secret=${CLOUDINARY_API_SECRET}
